from __future__ import annotations

import re

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def check_table(table: str) -> str:
    if not _IDENT.match(table):
        raise ValueError(f"table name must be a simple SQL identifier, got {table!r}")
    return table


def install_sql(table: str = "defer_jobs") -> str:
    """DDL for the job table and its indexes.

    Safe to run more than once. Put this in your own migrations if you
    do not want to call :meth:`deferjob.Defer.install`.
    """
    table = check_table(table)
    return f"""
CREATE TABLE IF NOT EXISTS {table} (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text NOT NULL,
    key           text,
    run_at        timestamptz NOT NULL,
    status        text NOT NULL DEFAULT 'pending',
    attempts      integer NOT NULL DEFAULT 0,
    max_attempts  integer NOT NULL DEFAULT 5,
    payload       jsonb NOT NULL DEFAULT jsonb_build_object(),
    last_error    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    locked_at     timestamptz,
    CONSTRAINT {table}_status_check
        CHECK (status IN ('pending', 'running', 'done', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS {table}_due
    ON {table} (run_at)
    WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS {table}_key
    ON {table} (key)
    WHERE key IS NOT NULL AND status IN ('pending', 'running');

CREATE INDEX IF NOT EXISTS {table}_reclaim
    ON {table} (locked_at)
    WHERE status = 'running';
""".strip()
